
# Actividad: Clasificación de imágenes naturales

¿Podemos clasificar imágenes naturales usando redes neuronales convolucionales?

En esta tarea usaremos la base de datos [CIFAR-10](https://www.cs.toronto.edu/~kriz/cifar.html)

Responda las preguntas y realice las actividades en cada uno de los bloques

Entregas al correo phuijse@inf.uach.cl hasta el Viernes 27, 11:20 AM

Se trabajará en grupos de dos personas: se entrega un notebook completo por grupo

### Base de datos

Descargue la base de datos usando `torchvision`

- ¿Cuántas categorías existen? 

Existen 10 categorías dentro del dataset

- ¿Cuántos ejemplos hay por categoría?

Se tienen 6000 datos por categoría

- ¿Cúantos ejemplos hay en el conjunto de entrenamiento? ¿Cúantos hay en el de test?

Para los datos de entrenamiento tnemos 50000 datos, y el conjunto de test tendremos 10000

- ¿De que tamaño son las imágenes?

El tamaño por cada imagen es de 32x32

- Muestre 5 ejemplos seleccionados aleatoriamente de cada categoría



In [1]:
import torch
import torchvision

cifar10_train = torchvision.datasets.CIFAR10(root='home/leo/datasets', train=True, download=True, transform=torchvision.transforms.ToTensor())
cifar10_test = torchvision.datasets.CIFAR10(root='home/leo/datasets', train=False,download=True, transform=torchvision.transforms.ToTensor())
display(cifar10_train)
display(cifar10_test)

Files already downloaded and verified
Files already downloaded and verified


Dataset CIFAR10
    Number of datapoints: 50000
    Root location: home/leo/datasets
    Split: Train

Dataset CIFAR10
    Number of datapoints: 10000
    Root location: home/leo/datasets
    Split: Test

In [2]:
display(cifar10_train[0][0])
display(cifar10_train[32][0])
display(cifar10_train[50][0])
display(cifar10_train[10][0])
display(cifar10_train[131][0])

tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
         [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
         [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
         ...,
         [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
         [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
         [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

        [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
         [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
         [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
         ...,
         [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
         [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
         [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

        [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
         [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
         [0.0824, 0.0000, 0.0314,  ..., 0.1961, 0.1961, 0.

tensor([[[0.1961, 0.2000, 0.1647,  ..., 0.1882, 0.0706, 0.0549],
         [0.3373, 0.3608, 0.3216,  ..., 0.1804, 0.0667, 0.0431],
         [0.1686, 0.1686, 0.2000,  ..., 0.1647, 0.0392, 0.0235],
         ...,
         [0.8627, 0.8196, 0.7804,  ..., 0.6941, 0.6902, 0.6863],
         [0.7373, 0.7137, 0.7137,  ..., 0.6902, 0.6863, 0.6824],
         [0.7373, 0.7216, 0.7294,  ..., 0.6902, 0.6902, 0.6784]],

        [[0.2510, 0.2471, 0.2157,  ..., 0.1765, 0.0706, 0.0588],
         [0.4196, 0.4314, 0.3882,  ..., 0.1686, 0.0667, 0.0471],
         [0.2353, 0.2196, 0.2549,  ..., 0.1529, 0.0392, 0.0235],
         ...,
         [0.6471, 0.6824, 0.6745,  ..., 0.6706, 0.6667, 0.6588],
         [0.6980, 0.6667, 0.6314,  ..., 0.6588, 0.6549, 0.6510],
         [0.6549, 0.6392, 0.6549,  ..., 0.6627, 0.6588, 0.6471]],

        [[0.1451, 0.1608, 0.1608,  ..., 0.1647, 0.0549, 0.0471],
         [0.2627, 0.2980, 0.2627,  ..., 0.1608, 0.0549, 0.0392],
         [0.1647, 0.1608, 0.1804,  ..., 0.1451, 0.0353, 0.

tensor([[[0.0627, 0.0667, 0.0667,  ..., 0.2431, 0.2157, 0.2000],
         [0.0627, 0.0627, 0.0588,  ..., 0.2431, 0.2275, 0.2039],
         [0.0627, 0.0588, 0.0588,  ..., 0.2235, 0.2314, 0.2196],
         ...,
         [0.3765, 0.4471, 0.4667,  ..., 0.5020, 0.4706, 0.4588],
         [0.4627, 0.3922, 0.4471,  ..., 0.5451, 0.5137, 0.4745],
         [0.5647, 0.5333, 0.4118,  ..., 0.5686, 0.5373, 0.5137]],

        [[0.2980, 0.3020, 0.3020,  ..., 0.4157, 0.3882, 0.3686],
         [0.2980, 0.2980, 0.2941,  ..., 0.4275, 0.4118, 0.3922],
         [0.2980, 0.2941, 0.2941,  ..., 0.4314, 0.4353, 0.4275],
         ...,
         [0.4314, 0.4980, 0.5176,  ..., 0.5294, 0.5098, 0.5137],
         [0.5176, 0.4431, 0.4941,  ..., 0.5725, 0.5490, 0.5255],
         [0.5804, 0.5490, 0.4471,  ..., 0.5922, 0.5647, 0.5529]],

        [[0.2902, 0.2941, 0.2941,  ..., 0.3412, 0.3137, 0.2941],
         [0.2902, 0.2902, 0.2902,  ..., 0.3294, 0.3137, 0.2941],
         [0.2902, 0.2863, 0.2863,  ..., 0.3098, 0.3137, 0.

tensor([[[0.2078, 0.2118, 0.2196,  ..., 0.1843, 0.1608, 0.0941],
         [0.1804, 0.2078, 0.2118,  ..., 0.1647, 0.1529, 0.1098],
         [0.1765, 0.1961, 0.1804,  ..., 0.1490, 0.1412, 0.1137],
         ...,
         [0.2784, 0.2902, 0.3137,  ..., 0.2000, 0.1804, 0.1922],
         [0.2941, 0.3098, 0.3176,  ..., 0.2392, 0.2510, 0.1882],
         [0.3333, 0.3333, 0.3373,  ..., 0.2392, 0.2510, 0.1922]],

        [[0.2549, 0.2471, 0.2353,  ..., 0.2000, 0.1765, 0.1098],
         [0.2314, 0.2431, 0.2314,  ..., 0.1804, 0.1686, 0.1255],
         [0.2314, 0.2353, 0.2039,  ..., 0.1647, 0.1569, 0.1294],
         ...,
         [0.3255, 0.3255, 0.3333,  ..., 0.2118, 0.1922, 0.1961],
         [0.3216, 0.3333, 0.3333,  ..., 0.2549, 0.2627, 0.1961],
         [0.3255, 0.3294, 0.3373,  ..., 0.2549, 0.2627, 0.1961]],

        [[0.2078, 0.2039, 0.1961,  ..., 0.1961, 0.1725, 0.1059],
         [0.1608, 0.1765, 0.1725,  ..., 0.1765, 0.1647, 0.1216],
         [0.1490, 0.1608, 0.1333,  ..., 0.1608, 0.1529, 0.

tensor([[[1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 1.0000],
         [1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [0.5255, 0.4431, 0.3373,  ..., 0.9647, 0.9882, 1.0000],
         [0.4118, 0.3137, 0.2706,  ..., 0.9843, 0.9882, 1.0000],
         [0.3333, 0.2510, 0.2275,  ..., 0.9647, 0.9490, 0.9647]],

        [[1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 1.0000],
         [1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [0.2784, 0.2196, 0.1882,  ..., 0.9412, 0.9686, 0.9961],
         [0.2000, 0.1294, 0.1490,  ..., 1.0000, 0.9961, 1.0000],
         [0.1608, 0.1137, 0.1137,  ..., 0.9412, 0.8980, 0.8784]],

        [[1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 1.0000],
         [1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.

detalles del dataset
https://www.cs.toronto.edu/~kriz/cifar.html

## Dataloaders

Construya `dataloaders` para el conjunto de entrenamiento y validación a partir del dataset `cifar10_train`

Construya un `dataloader` para el conjunto de test a partir del dataset `cifar10_test`

Use `shuffling` y tamaño de batch 32 para el conjunto de entrenamiento

In [3]:
from torch.utils.data import Subset, DataLoader
import sklearn.model_selection

In [4]:
# Set de entrenamiento y validación estratíficados
sss = sklearn.model_selection.StratifiedShuffleSplit(train_size=0.75).split(cifar10_train.data, cifar10_train.targets)
train_idx, valid_idx = next(sss)

# Create train data loader
train_dataset = Subset(cifar10_train, train_idx)
train_loader = DataLoader(train_dataset, shuffle=True, batch_size=32)

# Create valid data loader
valid_dataset = Subset(cifar10_train, valid_idx)
valid_loader = DataLoader(valid_dataset, shuffle=False, batch_size=256)

# Create test data loader
test_loader = DataLoader(cifar10_test, shuffle=False, batch_size=512)

## Red neuronal convolucional

Construya una clase que herede de `torch.nn.Module` y que implemente una red neuronal convolucional

Tome como base la arquitectura [Lenet5](http://yann.lecun.com/exdb/publis/pdf/lecun-01a.pdf) 
- Tres capas convolucionales cada una seguida de una capa de max-pooling
- Dos capas completamente conectadas
- Función de activación ReLU en todas las capas excepto en la última 
- Función de costo `CrossEntropyLoss`
- Optimizador `Adam`

Entrene su red en la base de datos CIFAR10
- Ajuste los parámetros con el conjunto de entrenamiento
- Evite el sobreajuste y calibre los hyper-parámetros en el conjunto de validación
- Muestre la calidad de su modelo evaluando en el conjunto de prueba

# Global parameters

In [5]:
nepochs = 20

# Training NN

In [6]:
import torch
print(torch.__version__)

# neural arquitechture
class diego_net_leo(torch.nn.Module):

    # init
    def __init__(self, n_hidden=20, n_filters=8):
        super(diego_net_leo, self).__init__()
        # Extracción de características
        self.conv1 = torch.nn.Conv2d(in_channels=3, out_channels=n_filters, kernel_size=3)
        self.conv2 = torch.nn.Conv2d(in_channels=n_filters, out_channels=16, kernel_size=3)
        self.conv3 = torch.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3)
        self.mpool = torch.nn.MaxPool2d(kernel_size=3, stride=2)
                
        # Clasificación
        self.fc1 = torch.nn.Linear(in_features=16, out_features=n_hidden)
        self.fc2 = torch.nn.Linear(in_features=n_hidden, out_features=10)
        self.activation = torch.nn.ReLU()
        
    def forward(self, x):
        
        #print("input: ",x.shape)
        #return x
        z = self.activation(self.conv1(x))
        
        #print("conv 1: ", z.shape)
        
        z = self.mpool(z)
        
        #print("pool 1: ", z.shape)
        
        z = self.activation(self.conv2(z))
        
        #print("conv 2: ", z.shape)
        
        z = self.mpool(z)
        
        #print("pool 2: ", z.shape)
        
        z = self.activation(self.conv3(z))
        
        #print("conv 3: ", z.shape)
        
        z = self.mpool(z)
        
        #print("pool 3: ", z.shape)
        
        z = z.reshape(-1, 16*1*1)
        
        #print("reshape: ", z.shape)
        
        z = self.activation(self.fc1(z))
        
        #print("fc1: ", z.shape)
        
        z = self.fc2(z)
        
        #print("fc2: ", z.shape)
        
        return z
    
# model = diego_net_leo()
# display(model.forward(cifar10_train[0][0].unsqueeze(0)))
# display(model)

1.1.0


In [7]:
# Define model
# model = diego_net_leo()
model = diego_net_leo().cuda()
# display(model.forward(cifar10_train[0][0].unsqueeze(0)))
# display(model)

In [8]:
# define loss function
criterion = torch.nn.CrossEntropyLoss(reduction='sum')

In [9]:
# define optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, amsgrad=True)

In [10]:
import numpy as np
import time
from tqdm import tqdm_notebook
from torch.utils.tensorboard import SummaryWriter

use_gpu = True
# nepochs = 2
best_valid = np.inf
writer = SummaryWriter(log_dir="/tmp/tensorboard/red_convolucional_simple"+str(time.time()),   flush_secs=20)

# Enviar modelo a la GPU
if use_gpu:
    model = model.cuda()

for k in tqdm_notebook(range(nepochs)):
    
    print("epoch: ", k)
    
    # Entrenamiento
    epoch_loss, epoch_acc = 0.0, 0.0
    
    for mbdata, mblabel in train_loader:
        
        if use_gpu:
            mbdata, mblabel = mbdata.cuda(), mblabel.cuda()
        # Inferencia
        prediction = model.forward(mbdata)
        # Estimar el error
        loss = criterion(prediction, mblabel)  
        epoch_loss += loss.item()
        epoch_acc += (torch.nn.Softmax(dim=1)(prediction).argmax(dim=1) == mblabel).sum().item()        
        # Calcular gradientes
        optimizer.zero_grad()        
        loss.backward()
        # Actualizar parámetros
        optimizer.step()
    # Enviar información a tensorboard
    writer.add_scalar('Train/Loss', epoch_loss/len(train_idx), k)
    writer.add_scalar('Train/Acc', epoch_acc/len(train_idx), k)
    # Validación
    epoch_loss, epoch_acc = 0.0, 0.0
    for mbdata, mblabel in valid_loader:
        if use_gpu:
            mbdata, mblabel = mbdata.cuda(), mblabel.cuda()
        # Inferencia
        prediction = model.forward(mbdata)
        # Estimar el error
        loss = criterion(prediction, mblabel)  
        epoch_loss += loss.item()
        epoch_acc += (torch.nn.Softmax(dim=1)(prediction).argmax(dim=1) == mblabel).sum().item()        
    # Enviar información a tensorboard
    writer.add_scalar('Valid/Loss', epoch_loss/len(valid_idx), k)
    writer.add_scalar('Valid/Acc', epoch_acc/len(valid_idx), k)
    
    if k % 5 == 0:
        if epoch_loss/len(valid_idx) < best_valid:
            print('new best model')
            best_valid = epoch_loss/len(valid_idx)
            torch.save({'epoca': k,
                        'model_state_dict': model.state_dict(),
                        'optimizer_state_dict': optimizer.state_dict(),                        
                        'loss': epoch_loss/len(valid_idx)}, 
                       'home/leo/models/best_model.pt') # MODIFICA LA RUTA 

# Retornar modelo a la CPU
if use_gpu:
    model = model.cpu()
    
writer.close()

epoch:  0
new best model
epoch:  1
epoch:  2
epoch:  3
epoch:  4
epoch:  5
new best model
epoch:  6
epoch:  7
epoch:  8
epoch:  9
epoch:  10
new best model
epoch:  11
epoch:  12
epoch:  13
epoch:  14
epoch:  15
new best model
epoch:  16
epoch:  17
epoch:  18
epoch:  19



In [18]:
# recovering best model
model = diego_net_leo()

model.load_state_dict(torch.load('home/leo/models/best_model.pt')['model_state_dict'])

IncompatibleKeys(missing_keys=[], unexpected_keys=[])

In [19]:
# Testing in test loader
# test_loader = DataLoader(cifar10_test, shuffle=False, batch_size=512)
# test_targets = cifar10_test.targets.numpy()
test_targets = cifar10_test.targets
prediction_test = []
for mbdata, label in test_loader:
    logits = model.forward(mbdata)
    prediction_test.append(torch.argmax(logits, dim=1).detach().numpy())

prediction_test = np.concatenate(prediction_test)

from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(test_targets, prediction_test)
display(cm)

print(classification_report(test_targets, prediction_test))

array([[591,  37,  79,  23,   9,  11,  31,  16, 149,  54],
       [ 64, 574,   4,  14,  11,   3,  23,  15,  59, 233],
       [ 89,   3, 323, 135,  88, 102, 165,  45,  29,  21],
       [ 25,  12,  99, 332,  23, 236, 162,  42,  33,  36],
       [ 45,  17, 158,  89, 248,  74, 220, 122,  13,  14],
       [ 15,   2,  87, 227,  29, 473,  74,  59,  17,  17],
       [ 11,   8,  34,  74,  32,  25, 778,  15,   8,  15],
       [ 23,  16,  36,  84,  50, 151,  38, 541,  12,  49],
       [158,  51,  23,  35,   2,   6,  11,   5, 639,  70],
       [ 32, 116,   4,  19,   3,   7,  28,  12,  72, 707]])

              precision    recall  f1-score   support

           0       0.56      0.59      0.58      1000
           1       0.69      0.57      0.63      1000
           2       0.38      0.32      0.35      1000
           3       0.32      0.33      0.33      1000
           4       0.50      0.25      0.33      1000
           5       0.43      0.47      0.45      1000
           6       0.51      0.78      0.62      1000
           7       0.62      0.54      0.58      1000
           8       0.62      0.64      0.63      1000
           9       0.58      0.71      0.64      1000

    accuracy                           0.52     10000
   macro avg       0.52      0.52      0.51     10000
weighted avg       0.52      0.52      0.51     10000



# Analisis de resultados sobre testing


## Aumentación de datos

Use `torchvision.transforms` para implementar una serie de transformaciones que aumenten el dataset de entrenamiento

Compare los resultados de la red entrenada en datos aumentados con la red entrenada en el conjunto regular

In [13]:
# Define transformations
transform = torchvision.transforms.Compose([
                                            torchvision.transforms.RandomHorizontalFlip(),
                                            torchvision.transforms.RandomRotation(degrees=50),
                                            torchvision.transforms.ColorJitter(brightness=0.5, contrast=0.5, 
                                                                               saturation=0.5, hue=0.0),
                                            torchvision.transforms.ToTensor()
                                           ])

In [14]:
# Create new train dataset
cifar10_train_augmented = torchvision.datasets.CIFAR10(
    root='home/leo/datasets', 
    train=True, download=False, 
    transform=transform)

In [15]:
# Define new loader

# Set de entrenamiento y validación estratíficados
sss = sklearn.model_selection.StratifiedShuffleSplit(train_size=0.75).split(cifar10_train_augmented.data, cifar10_train_augmented.targets)
train_idx, valid_idx = next(sss)

# Create train data loader
train_dataset_augmented = Subset(cifar10_train_augmented, train_idx)
train_loader_augmented = DataLoader(train_dataset_augmented, shuffle=True, batch_size=32)

# Create valid data loader
valid_dataset_augmented = Subset(cifar10_train_augmented, valid_idx)
valid_loader_augmented = DataLoader(valid_dataset_augmented, shuffle=False, batch_size=256)

In [16]:
# Define model 
model_augmented = diego_net_leo().cuda()

optimizer_augmented = torch.optim.Adam(model_augmented.parameters(), lr=1e-3, amsgrad=True)

# define loss function
criterion_augmented = torch.nn.CrossEntropyLoss(reduction='sum')

In [17]:
# Train model with augmented data
use_gpu = True
# nepochs = 2
best_valid = np.inf
# writer = SummaryWriter(log_dir="/tmp/tensorboard/red_convolucional_simple/"+str(time()),
#                        flush_secs=20)

# Enviar modelo a la GPU
if use_gpu:
    model_augmented = model_augmented.cuda()

for k in tqdm_notebook(range(nepochs)):
    
    # Entrenamiento
    epoch_loss, epoch_acc = 0.0, 0.0
    
    for mbdata, mblabel in train_loader_augmented:
        
        if use_gpu:
            mbdata, mblabel = mbdata.cuda(), mblabel.cuda()
        # Inferencia
        prediction = model_augmented.forward(mbdata)
        # Estimar el error
        loss = criterion_augmented(prediction, mblabel)  
        epoch_loss += loss.item()
        epoch_acc += (torch.nn.Softmax(dim=1)(prediction).argmax(dim=1) == mblabel).sum().item()        
        # Calcular gradientes
        optimizer_augmented.zero_grad()        
        loss.backward()
        # Actualizar parámetros
        optimizer_augmented.step()
    # Enviar información a tensorboard
#     writer.add_scalar('Train/Loss', epoch_loss/len(train_idx), k)
#     writer.add_scalar('Train/Acc', epoch_acc/len(train_idx), k)
    # Validación
    epoch_loss, epoch_acc = 0.0, 0.0
    for mbdata, mblabel in valid_loader_augmented:
        if use_gpu:
            mbdata, mblabel = mbdata.cuda(), mblabel.cuda()
        # Inferencia
        prediction = model_augmented.forward(mbdata)
        # Estimar el error
        loss = criterion_augmented(prediction, mblabel)  
        epoch_loss += loss.item()
        epoch_acc += (torch.nn.Softmax(dim=1)(prediction).argmax(dim=1) == mblabel).sum().item()        
#     # Enviar información a tensorboard
#     writer.add_scalar('Valid/Loss', epoch_loss/len(valid_idx), k)
#     writer.add_scalar('Valid/Acc', epoch_acc/len(valid_idx), k)
    
    if k % 5 == 0:
        if epoch_loss/len(valid_idx) < best_valid:
            best_valid = epoch_loss/len(valid_idx)
            torch.save({'epoca': k,
                        'model_state_dict': model_augmented.state_dict(),
                        'optimizer_state_dict': optimizer_augmented.state_dict(),                        
                        'loss': epoch_loss/len(valid_idx)}, 
                       'home/leo/models/best_model_augmented.pt') # MODIFICA LA RUTA 

# Retornar modelo a la CPU
if use_gpu:
    model_augmented = model_augmented.cpu()
    
# writer.close()

KeyboardInterrupt: 

In [ ]:
# recovering best model
model_augmented = diego_net_leo()

model_augmented.load_state_dict(torch.load('home/leo/models/best_model_augmented.pt')['model_state_dict'])

In [ ]:
# Testing in test loader
# test_targets = test_loader.targets.numpy()
test_targets = cifar10_test.targets
prediction_test_augmented = []
for mbdata, label in test_loader:
    logits_ = model_augmented.forward(mbdata)
    prediction_test_augmented.append(torch.argmax(logits_, dim=1).detach().numpy())

# print(prediction_test_augmented)

    
prediction_test_augmented = np.concatenate(prediction_test_augmented)

# print(prediction_test_augmented)

from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(test_targets, prediction_test_augmented)
display(cm)

print(classification_report(test_targets, prediction_test_augmented))

# Comparación entrenamiento con y sin aumentación

Agregar analisis 

## Propuestos (bonus)

- Implemente una arquitectura de tipo [AlexNet](http://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networ)
- Pruebe la eficacia de Dropout o Regularización L2 en los pesos